coverage:
  status:
    patch:
      default:
        target: 65%  # Match current coverage
        threshold: 5%  # Allow 5% deviation
    project:
      default:
        target: auto  # Maintain overall coverage
        threshold: 1%
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false